{
    'name': 'Alkeba B2C',
    'version': '1.0',
    'author': 'Alkeba',
    'category': 'Theme/eCommerce',
    'depends': [
        'website', 'sale_alkeba', 'website_blog', 'website_sale_wishlist', 'website_sale', 'stock', 'sale',
        'brand_alkeba', 'wishlist_alkeba', 'cart_alkeba', 'addres_alkeba', 'promo_alkeba'
    ],
    'data': [
        'data/delivery_carrier.xml',
        'data/format_paper_alkeba.xml',

        'security/ir.model.access.csv',

        'views/res_config_settings.xml',
        'views/product_category.xml',
        'views/product_template.xml',
        'views/sale_order.xml',
        'views/home_slider.xml',
        'views/home_event.xml',
        'views/menu.xml',

        'views/layouts.xml',
        'views/header.xml',
        # 'views/header_option1.xml',
        'views/footer.xml',
        'views/breadcrumbs.xml',
        'views/pagination.xml',
        'views/user_account_layout.xml',
        'views/index.xml',
        'views/commons.xml',
        'views/products.xml',
        'views/user_pages.xml',
        'views/cart.xml',
        'views/proceed_checkout.xml',
        'views/proceed_payment.xml',
        'views/proceed_payment_cod.xml',
        'views/blog.xml',
        'views/promo.xml',
        'views/promo_gift_detail.xml',
        'views/under_maintenance.xml',
        'views/detail_order_draft.xml',
        'views/detail_order_waiting_payment.xml',
        'views/detail_order_process.xml',
        'views/detail_order_deliver.xml',
        'views/detail_order_received.xml',
        'views/detail_order_done.xml',
        'views/users_update_profile.xml',
        'views/dashboard_users.xml',
        'views/res_partner.xml',
        'views/address_settings.xml',
        'views/wishlist.xml',
        'views/my_reviews.xml',
        'views/sale_report.xml',
        'views/invoice_waiting_payment.xml',
        'views/invoice_confirmation_va_payment.xml',
        'views/invoice_confirmation_bayartoko_payment.xml',
        'views/invoice_payment_success.xml',
        'views/invoice_order_process.xml',
        'views/invoice_order_send.xml',
        'views/invoice_order_done.xml',
        'views/signup.xml',
        'views/term_condition.xml',
        'views/res_users.xml',
        'views/notifications.xml',
        'views/order_tracking.xml',
        'views/order_tracking_detail.xml',
    ],
    'assets': {
        "web.assets_frontend": [
            # CSS
            # '/theme_alkeba/static/src/css/fontawesome-all.css',
            '/theme_alkeba/static/src/css/fonticon.css',
            '/theme_alkeba/static/src/css/bootstrap.min.css',
            # '/theme_alkeba/static/src/css/bootstrap-datepicker.min.css',
            # '/theme_alkeba/static/src/css/hierarchical-checkboxes.css',
            '/theme_alkeba/static/src/css/slick.css',
            '/theme_alkeba/static/src/css/select2.css',
            # Custom CSS
            '/theme_alkeba/static/src/css/custom-main-style.css',
            '/theme_alkeba/static/src/css/custom-mobile-style.css',
            
            # JS PLUGIN
            # '/theme_alkeba/static/src/js/jquery-3.1.0.js',  # CAUSING ERROR
            # 'https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js',
            # 'https://code.jquery.com/jquery-3.5.1.js',
            # 'https://code.jquery.com/ui/1.12.0/jquery-ui.min.js',

            # JS
            '/theme_alkeba/static/src/js/popper.min.js',
            '/theme_alkeba/static/src/js/bootstrap.min.js',
            '/theme_alkeba/static/src/js/slick.min.js',  # CAUSING ERROR
            '/theme_alkeba/static/src/js/hierarchical-checkboxes.js',
            # '/theme_alkeba/static/src/js/rangeslider.js',  # CAUSING ERROR
            '/theme_alkeba/static/src/js/jquery.fileupload.js',
            '/theme_alkeba/static/src/js/jquery.fancy-fileupload.js',
            # '/theme_alkeba/static/src/js/bootstrap-datepicker.min.js',
            # '/theme_alkeba/static/src/js/bootstrap-datepicker.js',
            '/theme_alkeba/static/src/js/multi-step-modal.js',
            '/theme_alkeba/static/src/js/select2.js',
            '/theme_alkeba/static/src/js/stick-kit.js',
            '/theme_alkeba/static/src/js/jquery.menu-aim.js',
            # Custom JS
            '/theme_alkeba/static/src/js/main.js',
            '/theme_alkeba/static/src/js/product-filter.js',
            '/theme_alkeba/static/src/js/wishlist.js',
            '/theme_alkeba/static/src/js/cart.js',
            '/theme_alkeba/static/src/js/users-profile.js',
            '/theme_alkeba/static/src/js/orders.js',
            '/theme_alkeba/static/src/js/product-list.js',
            '/theme_alkeba/static/src/js/livechat.js',
            '/theme_alkeba/static/src/js/address.js',
        ]
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
